### ISSUE TITLE
无法复合计算立直(双立直)与暗杠

### ISSUE THREAD

**Issue by GamesDownload** [ssttkkl/mahjong-utils-app#2]
计算规则里面无法复合立直与暗杠，希望可以增加结果显示每种役具体的番数，以及增加宝牌的类型和特殊役(比如八连庄，燕返之类的古役

**Comment by ssttkkl** [comment]
> 计算规则里面无法复合立直与暗杠

已修复

> 希望可以增加结果显示每种役具体的番数

之后的版本会考虑

> 增加宝牌的类型和特殊役(比如八连庄，燕返之类的古役

不会考虑
