### ISSUE TITLE
建议增加代码输入方式 可以复制粘贴

### ISSUE THREAD

**Issue by Cyiming** [ssttkkl/mahjong-utils-app#22]
比如p2446778s1122478

比选牌输入更快而且可复制粘贴

**Comment by ssttkkl** [comment]
使用键盘设备的时候确实是支持牌代码输入的，使用触屏的时候还不支持切换

**Comment by Cyiming** [comment]
> 使用键盘设备的时候确实是支持牌代码输入的，使用触屏的时候还不支持切换

电脑端粘贴不可以 输入能输入但没反应啊
![Clip_2024-08-24_10-14-28](https://github.com/user-attachments/assets/3bf7b927-205f-47c3-9e9d-b851eb686907)

**Comment by ssttkkl** [comment]
格式应该是1234s1234m456789s这样（一般都是这么输的吧

**Comment by ssttkkl** [comment]
#27 打通了系统剪切板实现复制粘贴

**Comment by Cyiming** [comment]
> 格式应该是1234s1234m456789s这样（一般都是这么输的吧

![Clip_2024-08-25_10-49-23](https://github.com/user-attachments/assets/4537b90f-97c5-4e53-ba74-3d9165608407)

兼容两种格式吧

**Comment by Cyiming** [comment]
> 没法兼容，很明显会有二义性（
> 
> > 格式应该是1234s1234m456789s这样（一般都是这么输的吧
> 
> 目前天凤雀魂以及我见过的麻将讨论的场景都是这种格式，所以只会考虑这种格式的牌代码

好吧 我平时用的网站是这种格式  看一些up分析用的代码也是这样 所以才有此提议 平时如果我说单牌会说7s 但写牌型会先声明是什么牌再写数字（仅仅表达我个人习惯 还是按照绝大多数人习惯来）

![Clip_2024-08-25_18-36-53](https://github.com/user-attachments/assets/c7d9ae77-25a2-40f1-8544-6b88428f9d5f)
