### ISSUE TITLE
English translation fixes

### ISSUE THREAD

**Issue by slashdevslashurandom** [ssttkkl/mahjong-utils-app#38]
I found out about your app on F-Droid and it seems to be very useful. However, there are some terms used in the English localization that will be confusing to the anglophone Riichi community.

Here are some examples:

The application uses the word "Hora" for what seems to be "winning hand" -- I am unable to find the proper definition of the term in online dictionaries. (The more proper term for "Hora Options", though, would probably be "Game Rule Options", as those are normally applied across the entire game.)

What the application refers to as "Furo" would normally be called an "open meld" (plural: "open melds"). The term "furo" is not used in the English community, even among people who know the Japanese names of every yaku.

Labeling "double riichi" as "WRiichi" will only make sense to people who know the Japanese custom of using the letter "W" as shorthand for "double" -- consider just writing "Double Riichi" or "DblRiichi" if brevity is required.

The "minipoints" referred to in some parts of the app as "hu" are more commonly called "fu".

**Comment by ssttkkl** [comment]
Thanks for your feedback! Actually I'm not very familiar with those Riichi Mahjong terminology in English.🥲
It would be grateful if you help me correct my Engligh translation in the whole project.

**Comment by ssttkkl** [comment]
contained here: https://github.com/ssttkkl/mahjong-utils-app/blob/main/composeApp/src/commonMain/composeResources/values/strings.xml

**Comment by ssttkkl** [comment]
Anyway I fix most English translation according to these English Riichi Mahjong rules:

- https://www.worldriichi.org/wrc-rules
- http://mahjong-europe.org/portal/index.php?option=com_content&view=article&id=30&Itemid=166

You can also check it.

**Comment by ssttkkl** [comment]
Fixed in [v1.0.11](https://github.com/ssttkkl/mahjong-utils-app/releases/tag/v1.0.11)
